/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kesmenapp.view.mahasiswa;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import kesmenapp.controller.authController;
import kesmenapp.controller.mahasiswaController;
import kesmenapp.model.Session;
import kesmenapp.view.HomeMahasiswa;
import kesmenapp.view.Login;

/**
 *
 * @author Dimas Haafizh Rahman
 */
public class Hasil extends javax.swing.JPanel {
    mahasiswaController mahasiswaController = new mahasiswaController();
    JScrollPane currentPanel;

    /**
     * Creates new form Hasil
     */
    public Hasil() {
        initComponents();
    }
    
    public Hasil(JScrollPane currentPanel) {
        initComponents();
        this.currentPanel = currentPanel;        
        mahasiswaController.tampilkanHasilTes(nilaiAkhirField, statusField, saranTextArea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nilaiAkhirField = new javax.swing.JTextField();
        statusField = new javax.swing.JTextField();
        saranTextArea = new javax.swing.JTextArea();
        tesUlangButton = new javax.swing.JButton();
        signOutButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nilaiAkhirField.setEditable(false);
        nilaiAkhirField.setBackground(new java.awt.Color(255, 255, 255));
        nilaiAkhirField.setForeground(new java.awt.Color(0, 0, 0));
        add(nilaiAkhirField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 100, 40));

        statusField.setEditable(false);
        statusField.setBackground(new java.awt.Color(255, 255, 255));
        statusField.setForeground(new java.awt.Color(0, 0, 0));
        add(statusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 100, 40));

        saranTextArea.setEditable(false);
        saranTextArea.setBackground(new java.awt.Color(255, 255, 255));
        saranTextArea.setColumns(20);
        saranTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saranTextArea.setForeground(new java.awt.Color(0, 0, 0));
        saranTextArea.setLineWrap(true);
        saranTextArea.setRows(5);
        add(saranTextArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 320, -1));

        tesUlangButton.setBackground(new java.awt.Color(0, 102, 204));
        tesUlangButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tesUlangButton.setForeground(new java.awt.Color(0, 0, 0));
        tesUlangButton.setText("Tes Ulang");
        tesUlangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tesUlangButtonActionPerformed(evt);
            }
        });
        add(tesUlangButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 90, 30));

        signOutButton.setBackground(new java.awt.Color(0, 102, 204));
        signOutButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signOutButton.setForeground(new java.awt.Color(0, 0, 0));
        signOutButton.setText("Sign Out");
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });
        add(signOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 90, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kesmenapp/view/icon/hasil.jpg"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void tesUlangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tesUlangButtonActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showOptionDialog(this, "Apakah Anda Ingin Melakukan Tes Ulang?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Tes Ulang", "Batal"}, "Tes Ulang") 
                == JOptionPane.YES_OPTION) {
            currentPanel.setViewportView(new HomeMahasiswa(currentPanel));
        }
        else return;
    }//GEN-LAST:event_tesUlangButtonActionPerformed

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showOptionDialog(this, "Apakah Anda Ingin Sign Out?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Sign Out", "Cancel"}, "Sign Out") 
                == JOptionPane.YES_OPTION) {
            authController.logout();
            currentPanel.setViewportView(new Login(currentPanel));
        }
        else return;
    }//GEN-LAST:event_signOutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField nilaiAkhirField;
    private javax.swing.JTextArea saranTextArea;
    private javax.swing.JButton signOutButton;
    private javax.swing.JTextField statusField;
    private javax.swing.JButton tesUlangButton;
    // End of variables declaration//GEN-END:variables
}
