/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kesmenapp.view.mahasiswa;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import kesmenapp.controller.mahasiswaController;
import kesmenapp.model.Mahasiswa;
import kesmenapp.model.Session;
import kesmenapp.view.Login;

/**
 *
 * @author Dimas Haafizh Rahman
 */
public class Pengerjaan extends javax.swing.JPanel {
    mahasiswaController mahasiswaController = new mahasiswaController();
    JScrollPane currentPanel;
    
    /**
     * Creates new form Pengerjaan
     */
    public Pengerjaan() {
        initComponents();
    }
    
    public Pengerjaan(JScrollPane currentPanel) {
        initComponents();
        this.currentPanel = currentPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1AnswerField = new javax.swing.JTextField();
        p2AnswerField = new javax.swing.JTextField();
        p3AnswerField = new javax.swing.JTextField();
        p4AnswerField = new javax.swing.JTextField();
        p5AnswerField = new javax.swing.JTextField();
        p6AnswerField = new javax.swing.JTextField();
        p7AnswerField = new javax.swing.JTextField();
        p8AnswerField = new javax.swing.JTextField();
        p9AnswerField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1AnswerField.setBackground(new java.awt.Color(255, 255, 255));
        p1AnswerField.setForeground(new java.awt.Color(0, 0, 0));
        p1AnswerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1AnswerFieldActionPerformed(evt);
            }
        });
        add(p1AnswerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 70, 30));

        p2AnswerField.setBackground(new java.awt.Color(255, 255, 255));
        p2AnswerField.setForeground(new java.awt.Color(0, 0, 0));
        add(p2AnswerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 70, -1));

        p3AnswerField.setBackground(new java.awt.Color(255, 255, 255));
        p3AnswerField.setForeground(new java.awt.Color(0, 0, 0));
        p3AnswerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3AnswerFieldActionPerformed(evt);
            }
        });
        add(p3AnswerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 70, -1));

        p4AnswerField.setBackground(new java.awt.Color(255, 255, 255));
        p4AnswerField.setForeground(new java.awt.Color(0, 0, 0));
        p4AnswerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4AnswerFieldActionPerformed(evt);
            }
        });
        add(p4AnswerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 70, -1));

        p5AnswerField.setBackground(new java.awt.Color(255, 255, 255));
        p5AnswerField.setForeground(new java.awt.Color(0, 0, 0));
        p5AnswerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5AnswerFieldActionPerformed(evt);
            }
        });
        add(p5AnswerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 70, -1));

        p6AnswerField.setBackground(new java.awt.Color(255, 255, 255));
        p6AnswerField.setForeground(new java.awt.Color(0, 0, 0));
        p6AnswerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6AnswerFieldActionPerformed(evt);
            }
        });
        add(p6AnswerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 70, -1));

        p7AnswerField.setBackground(new java.awt.Color(255, 255, 255));
        p7AnswerField.setForeground(new java.awt.Color(0, 0, 0));
        p7AnswerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p7AnswerFieldActionPerformed(evt);
            }
        });
        add(p7AnswerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 70, -1));

        p8AnswerField.setBackground(new java.awt.Color(255, 255, 255));
        p8AnswerField.setForeground(new java.awt.Color(0, 0, 0));
        p8AnswerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p8AnswerFieldActionPerformed(evt);
            }
        });
        add(p8AnswerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 70, -1));

        p9AnswerField.setBackground(new java.awt.Color(255, 255, 255));
        p9AnswerField.setForeground(new java.awt.Color(0, 0, 0));
        p9AnswerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p9AnswerFieldActionPerformed(evt);
            }
        });
        add(p9AnswerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 70, -1));

        submitButton.setBackground(new java.awt.Color(0, 102, 204));
        submitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitButton.setForeground(new java.awt.Color(0, 0, 0));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kesmenapp/view/icon/pengerjaan.jpg"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void p1AnswerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1AnswerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1AnswerFieldActionPerformed

    private void p4AnswerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4AnswerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p4AnswerFieldActionPerformed

    private void p5AnswerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5AnswerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p5AnswerFieldActionPerformed

    private void p3AnswerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3AnswerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p3AnswerFieldActionPerformed

    private void p6AnswerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6AnswerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p6AnswerFieldActionPerformed

    private void p7AnswerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p7AnswerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p7AnswerFieldActionPerformed

    private void p8AnswerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p8AnswerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p8AnswerFieldActionPerformed

    private void p9AnswerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p9AnswerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p9AnswerFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        int p1 = Integer.parseInt(p1AnswerField.getText());
        int p2 = Integer.parseInt(p2AnswerField.getText());
        int p3 = Integer.parseInt(p3AnswerField.getText());
        int p4 = Integer.parseInt(p4AnswerField.getText());
        int p5 = Integer.parseInt(p5AnswerField.getText());
        int p6 = Integer.parseInt(p6AnswerField.getText());
        int p7 = Integer.parseInt(p7AnswerField.getText());
        int p8 = Integer.parseInt(p8AnswerField.getText());
        int p9 = Integer.parseInt(p9AnswerField.getText());
        if (JOptionPane.showOptionDialog(this, "Apakah Anda Yakin dengan Jawaban Anda?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Ya", "Tidak"}, "Ya") 
                == JOptionPane.YES_OPTION) {
            mahasiswaController.inputTesMahasiswa(p1, p2, p3, p4, p5, p6, p7, p8, p9);
            currentPanel.setViewportView(new Hasil(currentPanel));
        }
        else return;
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField p1AnswerField;
    private javax.swing.JTextField p2AnswerField;
    private javax.swing.JTextField p3AnswerField;
    private javax.swing.JTextField p4AnswerField;
    private javax.swing.JTextField p5AnswerField;
    private javax.swing.JTextField p6AnswerField;
    private javax.swing.JTextField p7AnswerField;
    private javax.swing.JTextField p8AnswerField;
    private javax.swing.JTextField p9AnswerField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
