/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kesmenapp.view;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import kesmenapp.controller.adminController;
import kesmenapp.view.admin.Agregasi;
import kesmenapp.view.admin.HasilTes;

/**
 *
 * @author Dimas Haafizh Rahman
 */
public class HomeAdmin extends javax.swing.JPanel {
    adminController adminController = new adminController();
    JScrollPane currentPanel;
    
    /**
     * Creates new form HomeAdmin
     */
    public HomeAdmin() {
        initComponents();
    }
    
    public HomeAdmin(JScrollPane currentPanel) {
        initComponents();
        this.currentPanel = currentPanel;
        content.setViewportView(new HasilTes(content));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JScrollPane();
        signOutButton = new javax.swing.JButton();
        hasilTesButton = new javax.swing.JButton();
        agregasiButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 340, 260));

        signOutButton.setBackground(new java.awt.Color(0, 102, 204));
        signOutButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signOutButton.setForeground(new java.awt.Color(0, 0, 0));
        signOutButton.setText("Sign Out");
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });
        add(signOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 80, 30));

        hasilTesButton.setBackground(new java.awt.Color(0, 102, 204));
        hasilTesButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hasilTesButton.setForeground(new java.awt.Color(0, 0, 0));
        hasilTesButton.setText("Hasil Tes");
        hasilTesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilTesButtonActionPerformed(evt);
            }
        });
        add(hasilTesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, 30));

        agregasiButton.setBackground(new java.awt.Color(0, 102, 204));
        agregasiButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        agregasiButton.setForeground(new java.awt.Color(0, 0, 0));
        agregasiButton.setText("Agregasi");
        agregasiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregasiButtonActionPerformed(evt);
            }
        });
        add(agregasiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 80, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kesmenapp/view/icon/homeadmin.jpg"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showOptionDialog(this, "Apakah Anda Ingin Sign Out?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Sign Out", "Cancel"}, "Sign Out") 
                == JOptionPane.YES_OPTION) {
            currentPanel.setViewportView(new Login(currentPanel));
        }
        else return;
    }//GEN-LAST:event_signOutButtonActionPerformed

    private void agregasiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregasiButtonActionPerformed
        // TODO add your handling code here:
        content.setViewportView(new Agregasi(content));
    }//GEN-LAST:event_agregasiButtonActionPerformed

    private void hasilTesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilTesButtonActionPerformed
        // TODO add your handling code here:
        content.setViewportView(new HasilTes(content));
    }//GEN-LAST:event_hasilTesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregasiButton;
    private javax.swing.JLabel background;
    private javax.swing.JScrollPane content;
    private javax.swing.JButton hasilTesButton;
    private javax.swing.JButton signOutButton;
    // End of variables declaration//GEN-END:variables
}
