/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kesmenapp.view;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import kesmenapp.controller.adminController;
import kesmenapp.controller.authController;
import kesmenapp.controller.mahasiswaController;
import kesmenapp.model.Session;
import kesmenapp.view.mahasiswa.Pengerjaan;

/**
 *
 * @author Dimas Haafizh Rahman
 */
public class HomeMahasiswa extends javax.swing.JPanel {
    mahasiswaController mahasiswaController = new mahasiswaController();
    JScrollPane currentPanel;
    
    /**
     * Creates new form HomeMahasiswa
     */
    public HomeMahasiswa() {
        initComponents();
    }
    
    public HomeMahasiswa(JScrollPane currentPanel) {
        initComponents();
        this.currentPanel = currentPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        signOutButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startButton.setBackground(new java.awt.Color(0, 102, 204));
        startButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        startButton.setForeground(new java.awt.Color(0, 0, 0));
        startButton.setText("Mulai Tes");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        signOutButton.setBackground(new java.awt.Color(0, 102, 204));
        signOutButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signOutButton.setForeground(new java.awt.Color(0, 0, 0));
        signOutButton.setText("Sign Out");
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });
        add(signOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kesmenapp/view/icon/homemahasiswa.jpg"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        currentPanel.setViewportView(new Pengerjaan(currentPanel));
    }//GEN-LAST:event_startButtonActionPerformed

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showOptionDialog(this, "Apakah Anda Ingin Sign Out?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Sign Out", "Cancel"}, "Sign Out") 
                == JOptionPane.YES_OPTION) {
            authController.logout();
            currentPanel.setViewportView(new Login(currentPanel));
        }
        else return;
    }//GEN-LAST:event_signOutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton signOutButton;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
