/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kesmenapp.view;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import kesmenapp.controller.authController;

/**
 *
 * @author Dimas Haafizh Rahman
 */
public class SignUp extends javax.swing.JPanel {
    authController signUpController = new authController();
    JScrollPane currentPanel;

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }
    
    public SignUp(JScrollPane currentPanel) {
        initComponents();
        this.currentPanel = currentPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nimField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        namaField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        signUpButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nimField.setForeground(new java.awt.Color(0, 0, 0));
        add(nimField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 190, 30));

        emailField.setForeground(new java.awt.Color(0, 0, 0));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 190, 30));

        passwordField.setForeground(new java.awt.Color(0, 0, 0));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 190, 30));

        namaField.setForeground(new java.awt.Color(0, 0, 0));
        namaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaFieldActionPerformed(evt);
            }
        });
        add(namaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 190, 30));

        cancelButton.setBackground(new java.awt.Color(0, 102, 204));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(0, 0, 0));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 80, 30));

        signUpButton1.setBackground(new java.awt.Color(0, 102, 204));
        signUpButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signUpButton1.setForeground(new java.awt.Color(0, 0, 0));
        signUpButton1.setText("Sign Up");
        signUpButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButton1ActionPerformed(evt);
            }
        });
        add(signUpButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 80, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kesmenapp/view/icon/signuppage.jpg"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void namaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaFieldActionPerformed

    private void signUpButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButton1ActionPerformed
        // TODO add your handling code here:
        String nim = nimField.getText().toString();
        String nama = namaField.getText().toString();
        String email = emailField.getText().toString();
        String password = passwordField.getText();
        
        if (signUpController.validateFieldSignUp(nim, nama, email, password)) {
            JOptionPane.showMessageDialog(this, "Semua Field Wajib Diisi", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String msg = signUpController.signUp(nim, nama, email, password);
        JOptionPane.showMessageDialog(this, msg);
        if (msg.equals("Sign Up Berhasil!")) {
            currentPanel.setViewportView(new Login(currentPanel));
        }
    }//GEN-LAST:event_signUpButton1ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        currentPanel.setViewportView(new Login(currentPanel));
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField namaField;
    private javax.swing.JTextField nimField;
    private javax.swing.JTextField passwordField;
    private javax.swing.JButton signUpButton1;
    // End of variables declaration//GEN-END:variables
}
