/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kesmenapp.view.admin;

import com.itextpdf.text.DocumentException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import kesmenapp.controller.adminController;

/**
 *
 * @author Dimas Haafizh Rahman
 */
public class HasilTes extends javax.swing.JPanel {
    adminController adminController = new adminController();
    JScrollPane content;
    
    /**
     * Creates new form HasilTes
     */
    public HasilTes() {
        initComponents();
    }
    
    public HasilTes(JScrollPane content) {
        initComponents();
        this.content = content;
        DefaultTableModel dtm = (DefaultTableModel) tesMahasiswaTable.getModel();
        adminController.loadTableData(dtm);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tesMahasiswaTable = new javax.swing.JTable();
        exportButton = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        setBackground(new java.awt.Color(153, 204, 255));
        setForeground(new java.awt.Color(0, 153, 204));

        tesMahasiswaTable.setBackground(new java.awt.Color(255, 255, 255));
        tesMahasiswaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID Tes", "NIM", "Nilai Akhir", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tesMahasiswaTable.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tesMahasiswaTable);

        exportButton.setBackground(new java.awt.Color(0, 102, 204));
        exportButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exportButton.setForeground(new java.awt.Color(0, 0, 0));
        exportButton.setText("Export");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(exportButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(exportButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tesMahasiswaTable.getModel();
        try {
            adminController.export(dtm);
        } catch (DocumentException ex) {
            Logger.getLogger(HasilTes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_exportButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exportButton;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tesMahasiswaTable;
    // End of variables declaration//GEN-END:variables
}
